# Generated by Django 3.2.9 on 2022-04-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='numero',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
