# Generated by Django 3.2.9 on 2022-04-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestra', '0002_alter_muestra_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muestra',
            name='id',
        ),
        migrations.AddField(
            model_name='muestra',
            name='name',
            field=models.CharField(default=1, max_length=3, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
