# Generated by Django 3.2.9 on 2022-04-10 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muestra', '0003_auto_20220410_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muestra',
            name='numero',
        ),
    ]
