# Generated by Django 3.2.9 on 2022-04-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestra', '0005_auto_20220410_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='descripcion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='muestra',
            name='fecha',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='muestra',
            name='titulo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
