# Generated by Django 3.2.9 on 2022-04-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestra', '0006_auto_20220411_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='descripcion',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
