# Generated by Django 3.2.9 on 2022-04-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obras',
            old_name='numero',
            new_name='codigo',
        ),
        migrations.AddField(
            model_name='obras',
            name='precio',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='tecnica',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='obras',
            name='apellido',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='obras',
            name='fecha',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='obras',
            name='firma',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='obras',
            name='imagen',
            field=models.ImageField(null=True, upload_to='obras'),
        ),
        migrations.AlterField(
            model_name='obras',
            name='medidas',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='obras',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='obras',
            name='titulo',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
