# Generated by Django 3.2.9 on 2022-04-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0003_remove_obras_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='muestra',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
