# Generated by Django 3.2.9 on 2022-04-11 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muestra', '0005_auto_20220410_2057'),
        ('obras', '0005_alter_obras_muestra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obras',
            name='muestra',
            field=models.ForeignKey(choices=[(3, 'coco'), (1, 'jorge iglesias')], default=(3, 'coco'), null=True, on_delete=django.db.models.deletion.CASCADE, to='muestra.muestra'),
        ),
    ]
