# Generated by Django 3.2.9 on 2022-04-11 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muestra', '0007_alter_muestra_descripcion'),
        ('obras', '0007_alter_obras_muestra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obras',
            name='muestra',
            field=models.ForeignKey(default=(1, 'jorge iglesias'), null=True, on_delete=django.db.models.deletion.CASCADE, to='muestra.muestra'),
        ),
    ]
