# Generated by Django 3.2.9 on 2022-04-08 17:45

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('portada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portada',
            name='obra1',
            field=models.ImageField(null=sqlalchemy.sql.expression.false, upload_to=''),
            preserve_default=sqlalchemy.sql.expression.false,
        ),
        migrations.AddField(
            model_name='portada',
            name='obra2',
            field=models.ImageField(null=sqlalchemy.sql.expression.false, upload_to=''),
            preserve_default=sqlalchemy.sql.expression.false,
        ),
    ]
