# Generated by Django 3.2.9 on 2022-04-08 18:02

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('portada', '0002_auto_20220408_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portada',
            name='obra1',
            field=models.ImageField(null=sqlalchemy.sql.expression.false, upload_to='portada'),
        ),
        migrations.AlterField(
            model_name='portada',
            name='obra2',
            field=models.ImageField(null=sqlalchemy.sql.expression.false, upload_to='portada'),
        ),
    ]
