# Generated by Django 3.2.9 on 2022-04-08 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portada', '0003_auto_20220408_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portada',
            options={'verbose_name': 'Portada', 'verbose_name_plural': 'Portadas'},
        ),
    ]
