# Generated by Django 3.2.9 on 2022-04-08 20:26

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('portada', '0004_alter_portada_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='portada',
            name='titulo',
            field=models.CharField(max_length=50, null=sqlalchemy.sql.expression.false),
            preserve_default=sqlalchemy.sql.expression.false,
        ),
    ]
