# Generated by Django 3.2.9 on 2022-04-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portada', '0006_portada_opcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portada',
            name='opcion',
            field=models.CharField(choices=[('MUESTRA', 'Muestra'), ('SUBASTA', 'Subasta')], max_length=30),
        ),
    ]
