# Generated by Django 3.2.9 on 2022-04-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portada', '0008_remove_portada_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='portada',
            name='evento',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
